[tool.black]
line-length = 120

[tool.isort]
profile = "black"
multi_line_output = 3
force_single_line = false
line_length = 9999

[tool.autoflake]
in-place = true
remove-all-unused-imports = true
remove-unused-variables = true
recursive = true